class AppStrings {
  static const String appName = 'Home Services';
  static const String poppins = 'Poppins';
  static const String splashDesc = 'Finding and connecting with trusted local professionals around you.';
  static const String skipThisStep = 'Skip this step';
  static const String signUp = 'Sign up';
  static const String login  = 'Login';
  static const String backToLogin  = 'Back to login';
  static const String continue_  = 'Continue';
  static const String next  = 'Next';
  static const String signUpToHome  = 'Sign up to Home';
  static const String loginToYourAccount  = 'Login to your account';
  static const String forgotPassword  = 'Forgot Password';
  static const String completeYourInfo  = 'Complete your info';
  static const String show  = 'Show';
  static const String mobileNumber  = 'Mobile Number';
  static const String or = 'OR';
  static const String continueWithGmail = 'Continue with gmail';
  static const String continueWithWhatsApp = 'Continue with WhatsApp';
  static const String firstName  = 'First Name';
  static const String lastName  = 'Last Name';
  static const String password  = 'Password';
  static const String confirmPassword  = 'Confirm Password';
  static const String termsAndPrivacy  = 'By selecting Next, i agree to  Home’s  terms of service, Payment Terms of Service & Privacy Policy.';
  static const String allowLocationAccess  = 'Allow location access';
  static const String locationAccessDesc  = 'We need your location access to easily find Home professionals around you.';
  static const String resetPasswordDesc  = 'We will sent OTP code to your Whatsapp number.';
  static const String letsResetYourPassword  = 'Let’s reset your password.';
  static const String checkYourWhatsapp  = 'Check your Whatsapp';
  static const String checkYourWhatsappDesc  = 'We sent a OTP code to 010********6 number on whatsapp';
  static const String ifYouDontReceiveCode = 'if you don’t Receive a code click on bleow.';
  static const String resendLink = 'Resend Link';
  static const String verifyYourPhoneNumber = 'Verify your phone number';
  static const String enterTheCode = 'Enter the code that was sent to your WhatsApp number';
  static const String number = '+234 808 547 2417';
  static const String didNotReceiveTheCode = 'Did not receive the code?';
  static const String resendCode = 'Resend Code';

}